# Generated by Django 5.2.2 on 2025-06-28 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_bmirecord_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='bmirecord',
            name='status',
            field=models.CharField(default='Unknown', max_length=20),
        ),
    ]
