# Generated by Django 5.2.2 on 2025-07-01 10:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_bmirecord_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bmirecord',
            name='status',
            field=models.CharField(max_length=50),
        ),
    ]
